---
- name: Get VM Metadata from BIOS UUID
  hosts: all
  become: yes
  vars:
    metadata_url: "https://apiv4.plusclouds.com/public/iaas/virtual-machines/meta-data?uuid="
  tasks:
    - name: Get BIOS UUID
      command: dmidecode -s system-uuid
      register: bios_uuid_raw
      changed_when: false

    - name: Clean BIOS UUID
      set_fact:
        bios_uuid: "{{ bios_uuid_raw.stdout | trim }}"

    - name: Display BIOS UUID (Debug)
      debug:
        msg: "BIOS UUID is {{ bios_uuid }}"

    - name: Query metadata service using BIOS UUID
      uri:
        url: "{{ metadata_url }}{{ bios_uuid }}"
        method: GET
        return_content: yes
        status_code: 200
        headers:
          Accept: "application/json"
      register: metadata_response

    - name: Show metadata response
      debug:
        var: metadata_response.json

    - name: Extract values from metadata
      set_fact:
        vm_user: "{{ metadata_response.json.username }}"
        vm_password: "{{ metadata_response.json.password }}"

    - name: Apply password configuration
      include_tasks: change-password.yml

    - name: Extract values for hostname configuration
      set_fact:
        hostname: "{{ metadata_response.json.hostname | default('default-hostname') }}"

    - name: Apply hostname configuration
      include_tasks: change-hostname.yml